@startuml
'https://plantuml.com/component-diagram

class Scan {
    scanid: int {PK}
    time: DateTime
    source: Varchar[256]
    wordCount: int
    charCount: int
    longestWord: Varchar[256]
}

class wordmap {
    scanid: int {PK,FK}
    word: varchar[256] {PK}
    count: int
}

class charmap {
    scanid: id {PK, FK}
    char: char[1] {PK}
    count: int
}

Scan "*"--"1" wordmap
Scan "*"--"1  " charmap

@enduml