@startuml
'https://plantuml.com/class-diagram

UnitInterface -- Facade

Facade - Analizer
Facade -- FileReader
Facade -- Database


class UnitInterface {
}

class Facade {
}

class Analizer {
}

class FileReader {
}

class Database {
}

@enduml