@startuml
'https://plantuml.com/sequence-diagram

'participents
actor User
participant MainManager
entity AnalyzerManager
collections FileManager
database DB

group Init 

activate MainManager #grey

MainManager -> FileManager: Init
activate FileManager
FileManager -> FileManager: Create 'Resources'\nif folder doesn't\nexists
return

MainManager -> DB: Init
activate DB
ref over DB: Create DB\nif not exists
return

end group

loop Main loop

alt New Scan

MainManager -> User: Get Action
activate User

return New Scan

MainManager -> FileManager: Analyze text
activate FileManager

    FileManager -> User: Select a file
    activate User
    return selection
    
return file handle
    
MainManager -> AnalyzerManager
    activate AnalyzerManager
    ref over AnalyzerManager: multithreaded analyze
return

alt save scan
FileManager -> User: Result + SaveScan?
activate User
return save

MainManager -> DB: Result
    activate DB
    ref over DB: Save scan
return
    
else dont save
FileManager -> User: Result + SaveScan?
activate User
return dont save

end alt

else Get text stats

MainManager -> User: Get action
activate User
return Get text stats

MainManager -> DB: Get saved scans list
activate DB
return List



end alt

end loop
@enduml