@startuml
'https://plantuml.com/sequence-diagram

'participents
actor User
participant MainManager
entity AnalyzerManager
collections FileManager
database DB

autoactivate on

activate MainManager 

group Init 

MainManager -> FileManager: Init
note over FileManager: Create 'Resources'\nif folder doesn't\nexists
return

MainManager -> DB: Init
ref over DB: Create DB\nif not exists
return

end group

loop Main loop

alt New Scan

MainManager -> User: Get Action
return New Scan

MainManager -> FileManager: Analyze text
    FileManager -> User: Select a file
    return selection
    
return file handle
    
MainManager -> AnalyzerManager
    ref over AnalyzerManager: multithreaded analyze
return

alt save scan
MainManager -> User: Result + SaveScan?
return save

MainManager -> DB: Result
    ref over DB: Save scan
return
    
else dont save
MainManager -> User: Result + SaveScan?
return dont save

end alt

else Get text stats

MainManager -> User: Get action
return Get text stats

MainManager -> DB: Get saved scans list
return List

MainManager -> User: List
return Selected scan

MainManager -> DB: Get Saved Scan
return Scan

MainManager -> User: Scan

end alt

end loop
@enduml